#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Ladder

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass AnimBP_Ladder.AnimBP_Ladder_C
// 0x02B0 (0x0570 - 0x02C0)
class UAnimBP_Ladder_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose_2;                      // 0x02F8(0x0018)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0310(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_4;                              // 0x03D0(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x0418(0x0048)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose_1;                      // 0x0460(0x0018)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose;                        // 0x0478(0x0018)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x0490(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x04D8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0520(0x0048)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_AnimBP_Ladder(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AnimBP_Ladder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimBP_Ladder_C")
	}
	static class UAnimBP_Ladder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_Ladder_C>();
	}
};
DUMPER7_ASSERTS_UAnimBP_Ladder_C;

SDK_NAMESPACE_END
