#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Ladder

#include "Basic.hpp"

#include "AnimBP_Ladder_classes.hpp"
#include "AnimBP_Ladder_parameters.hpp"


SDK_NAMESPACE_START

// Function AnimBP_Ladder.AnimBP_Ladder_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_Ladder_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Ladder_C", "AnimGraph");

	Params::AnimBP_Ladder_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_Ladder.AnimBP_Ladder_C.ExecuteUbergraph_AnimBP_Ladder
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_Ladder_C::ExecuteUbergraph_AnimBP_Ladder(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_Ladder_C", "ExecuteUbergraph_AnimBP_Ladder");

	Params::AnimBP_Ladder_C_ExecuteUbergraph_AnimBP_Ladder Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
