#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_SetMaxDrawDistance

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BFL_SetMaxDrawDistance.BFL_SetMaxDrawDistance_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_SetMaxDrawDistance_C final : public UBlueprintFunctionLibrary
{
public:
	static void Set_Instance_Draw_Distance(bool EnableCullDistances, class UInstancedStaticMeshComponent* InstancedStaticMesh, TArray<struct FCullDistanceSizePair>& CullDistances, class UStaticMesh* StaticMesh, float FalloffPercentage, class UObject* __WorldContext);
	static void ReverseSortCullDistances(TArray<struct FCullDistanceSizePair>& CullDistances, class UObject* __WorldContext, TArray<struct FCullDistanceSizePair>* SortedCullDistances);
	static void GetObjectBoundsSize(class UStaticMeshComponent* StaticMesh, float Scale, bool Debug, class UObject* __WorldContext, float* Size);
	static void Set_Max_Draw_Distance(bool EnableCullDistances, TArray<class UStaticMeshComponent*>& StaticMeshes, TArray<struct FCullDistanceSizePair>& CullDistances, float ScaleMin, float ScaleMax, float ScaleUniform, bool Debug, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_SetMaxDrawDistance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_SetMaxDrawDistance_C")
	}
	static class UBFL_SetMaxDrawDistance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_SetMaxDrawDistance_C>();
	}
};
DUMPER7_ASSERTS_UBFL_SetMaxDrawDistance_C;

SDK_NAMESPACE_END
