#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_SetMaxDrawDistance

#include "Basic.hpp"

#include "BFL_SetMaxDrawDistance_classes.hpp"
#include "BFL_SetMaxDrawDistance_parameters.hpp"


SDK_NAMESPACE_START

// Function BFL_SetMaxDrawDistance.BFL_SetMaxDrawDistance_C.Set Instance Draw Distance
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableCullDistances                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UInstancedStaticMeshComponent*    InstancedStaticMesh                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FCullDistanceSizePair>&   CullDistances                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UStaticMesh*                      StaticMesh                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   FalloffPercentage                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBFL_SetMaxDrawDistance_C::Set_Instance_Draw_Distance(bool EnableCullDistances, class UInstancedStaticMeshComponent* InstancedStaticMesh, TArray<struct FCullDistanceSizePair>& CullDistances, class UStaticMesh* StaticMesh, float FalloffPercentage, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BFL_SetMaxDrawDistance_C", "Set Instance Draw Distance");

	Params::BFL_SetMaxDrawDistance_C_Set_Instance_Draw_Distance Parms{};

	Parms.EnableCullDistances = EnableCullDistances;
	Parms.InstancedStaticMesh = InstancedStaticMesh;
	Parms.CullDistances = std::move(CullDistances);
	Parms.StaticMesh = StaticMesh;
	Parms.FalloffPercentage = FalloffPercentage;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	CullDistances = std::move(Parms.CullDistances);
}


// Function BFL_SetMaxDrawDistance.BFL_SetMaxDrawDistance_C.ReverseSortCullDistances
// (Static, Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FCullDistanceSizePair>&   CullDistances                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FCullDistanceSizePair>*   SortedCullDistances                                    (Parm, OutParm)

void UBFL_SetMaxDrawDistance_C::ReverseSortCullDistances(TArray<struct FCullDistanceSizePair>& CullDistances, class UObject* __WorldContext, TArray<struct FCullDistanceSizePair>* SortedCullDistances)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BFL_SetMaxDrawDistance_C", "ReverseSortCullDistances");

	Params::BFL_SetMaxDrawDistance_C_ReverseSortCullDistances Parms{};

	Parms.CullDistances = std::move(CullDistances);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	CullDistances = std::move(Parms.CullDistances);

	if (SortedCullDistances != nullptr)
		*SortedCullDistances = std::move(Parms.SortedCullDistances);
}


// Function BFL_SetMaxDrawDistance.BFL_SetMaxDrawDistance_C.GetObjectBoundsSize
// (Static, Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMeshComponent*             StaticMesh                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Scale                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Debug                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Size                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBFL_SetMaxDrawDistance_C::GetObjectBoundsSize(class UStaticMeshComponent* StaticMesh, float Scale, bool Debug, class UObject* __WorldContext, float* Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BFL_SetMaxDrawDistance_C", "GetObjectBoundsSize");

	Params::BFL_SetMaxDrawDistance_C_GetObjectBoundsSize Parms{};

	Parms.StaticMesh = StaticMesh;
	Parms.Scale = Scale;
	Parms.Debug = Debug;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Size != nullptr)
		*Size = Parms.Size;
}


// Function BFL_SetMaxDrawDistance.BFL_SetMaxDrawDistance_C.Set Max Draw Distance
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableCullDistances                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class UStaticMeshComponent*>&    StaticMeshes                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// TArray<struct FCullDistanceSizePair>&   CullDistances                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   ScaleMin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ScaleMax                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ScaleUniform                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Debug                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBFL_SetMaxDrawDistance_C::Set_Max_Draw_Distance(bool EnableCullDistances, TArray<class UStaticMeshComponent*>& StaticMeshes, TArray<struct FCullDistanceSizePair>& CullDistances, float ScaleMin, float ScaleMax, float ScaleUniform, bool Debug, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BFL_SetMaxDrawDistance_C", "Set Max Draw Distance");

	Params::BFL_SetMaxDrawDistance_C_Set_Max_Draw_Distance Parms{};

	Parms.EnableCullDistances = EnableCullDistances;
	Parms.StaticMeshes = std::move(StaticMeshes);
	Parms.CullDistances = std::move(CullDistances);
	Parms.ScaleMin = ScaleMin;
	Parms.ScaleMax = ScaleMax;
	Parms.ScaleUniform = ScaleUniform;
	Parms.Debug = Debug;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	StaticMeshes = std::move(Parms.StaticMeshes);
	CullDistances = std::move(Parms.CullDistances);
}


SDK_NAMESPACE_END
