#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AttemptToEnterLobby_Flow

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"
#include "Backrooms_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.ExecuteUbergraph_BP_AttemptToEnterLobby_Flow
// 0x0240 (0x0240 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_ExecuteUbergraph_BP_AttemptToEnterLobby_Flow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const bool SessionInfo)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	EOnJoinSessionCompleteFancyResult             K2Node_CustomEvent_Result;                         // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOnJoinSessionCompleteFancyResult             Temp_byte_Variable;                                // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOnJoinSessionCompleteFancyResult             Temp_byte_Variable_1;                              // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17[0x1];                                       // 0x0017(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0018(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_1;                              // 0x0030(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_2;                              // 0x0048(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_3;                              // 0x0060(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_4;                              // 0x0078(0x0018)(ConstParm)
	class FText                                   Temp_text_Variable_5;                              // 0x0090(0x0018)(ConstParm)
	class FText                                   K2Node_Select_Default;                             // 0x00A8(0x0018)(ConstParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00C0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00D0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool bSuccess)>                K2Node_CreateDelegate_OutputDelegate_5;            // 0x0100(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(EOnJoinSessionCompleteFancyResult Result)> K2Node_CreateDelegate_OutputDelegate_6; // 0x0110(0x0010)(ZeroConstructor, NoDestructor)
	EOnJoinSessionCompleteFancyResult             K2Node_CustomEvent_Result_1;                       // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_121[0x3];                                      // 0x0121(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EOnJoinSessionCompleteFancyResult Result)> K2Node_CreateDelegate_OutputDelegate_7; // 0x0124(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsConsoleBuild_ReturnValue;               // 0x0134(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0135(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0136(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0137(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FBPUniqueNetId                         CallFunc_GetUniqueNetID_UniqueNetId;               // 0x0138(0x0028)()
	struct FBPUniqueNetId                         CallFunc_BPTryGetPlatformNetIDFromCachedID_ReturnValue; // 0x0160(0x0028)()
	class UCheckSubscriptionCallbackProxy*        CallFunc_CheckSubscription_ReturnValue;            // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x7];                                      // 0x0191(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MyGameInstance_C*                   CallFunc_GetGameInstance_ReturnValue;              // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFancyJoinSessionCallbackProxy*         CallFunc_FancyJoinSession_ReturnValue;             // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MyGameInstance_C*                   CallFunc_GetGameInstance_ReturnValue_1;            // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFancyDestroySessionCallbackProxy*      CallFunc_FancyDestroySession_ReturnValue;          // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFancyDestroySessionCallbackProxy*      CallFunc_FancyDestroySession_ReturnValue_1;        // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x01C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_SessionInfo;                    // 0x01CA(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1CB[0x5];                                      // 0x01CB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MyGameInstance_C*                   CallFunc_GetGameInstance_ReturnValue_2;            // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetFocusedWidget_ReturnValue;             // 0x01D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const bool SessionInfo)>       K2Node_CreateDelegate_OutputDelegate_8;            // 0x01E0(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FSessionPropertyKeyPair>        CallFunc_GetExtraSettings_ExtraSettings;           // 0x01F0(0x0010)(ReferenceParm)
	bool                                          CallFunc_CanCrossPlay_CanCrossplay;                // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESessionSettingSearchResult                   CallFunc_GetSessionPropertyString_SearchResult;    // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_202[0x6];                                      // 0x0202(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetSessionPropertyString_SettingValue;    // 0x0208(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EFancyPlatform                                CallFunc_GetPlatformFromString_ReturnValue;        // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0219(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsCompatiblePlatform_ReturnValue;         // 0x021A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESessionSettingSearchResult                   CallFunc_GetSessionPropertyBool_SearchResult;      // 0x021B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSessionPropertyBool_SettingValue;      // 0x021C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue;          // 0x021D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x021E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESessionSettingSearchResult                   CallFunc_GetSessionPropertyBool_SearchResult_1;    // 0x021F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSessionPropertyBool_SettingValue_1;    // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue_1;        // 0x0221(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_2;                    // 0x0222(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanPlayOnline_CanPlayOnline;              // 0x0223(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_224[0x4];                                      // 0x0224(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetFocusedWidget_ReturnValue_1;           // 0x0228(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MyGameInstance_C*                   CallFunc_GetGameInstance_ReturnValue_3;            // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFancyPlatform                                CallFunc_GetPlatform_ReturnValue;                  // 0x0238(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_3;                    // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bSuccess;                       // 0x023A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_SessionInfo_1;                  // 0x023B(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_ExecuteUbergraph_BP_AttemptToEnterLobby_Flow;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.HandleCrossplayPrivilegeCheckComplete
// 0x0001 (0x0001 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_HandleCrossplayPrivilegeCheckComplete final
{
public:
	bool                                          bSuccess_0;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_HandleCrossplayPrivilegeCheckComplete;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.OnSuccess_1ADC80B6492FC6B5A0960B9340AF9E0E
// 0x0001 (0x0001 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_OnSuccess_1ADC80B6492FC6B5A0960B9340AF9E0E final
{
public:
	EOnJoinSessionCompleteFancyResult             Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_OnSuccess_1ADC80B6492FC6B5A0960B9340AF9E0E;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.OnFailure_1ADC80B6492FC6B5A0960B9340AF9E0E
// 0x0001 (0x0001 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_OnFailure_1ADC80B6492FC6B5A0960B9340AF9E0E final
{
public:
	EOnJoinSessionCompleteFancyResult             Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_OnFailure_1ADC80B6492FC6B5A0960B9340AF9E0E;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.OnSuccess_1AF601CC4208579E90FF82B097455828
// 0x0001 (0x0001 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_OnSuccess_1AF601CC4208579E90FF82B097455828 final
{
public:
	bool                                          SessionInfo;                                       // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_OnSuccess_1AF601CC4208579E90FF82B097455828;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.OnFailure_1AF601CC4208579E90FF82B097455828
// 0x0001 (0x0001 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_OnFailure_1AF601CC4208579E90FF82B097455828 final
{
public:
	bool                                          SessionInfo;                                       // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_OnFailure_1AF601CC4208579E90FF82B097455828;

// Function BP_AttemptToEnterLobby_Flow.BP_AttemptToEnterLobby_Flow_C.CompleteAndReturnFocus
// 0x0020 (0x0020 - 0x0000)
struct BP_AttemptToEnterLobby_Flow_C_CompleteAndReturnFocus final
{
public:
	TArray<class UW_MainMenu_ServerList_C*>       CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0000(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UW_MainMenu_ServerList_C*               CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_AttemptToEnterLobby_Flow_C_CompleteAndReturnFocus;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
