#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BalanceZone

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BalanceZone.BP_BalanceZone_C
// 0x0008 (0x0230 - 0x0228)
class ABP_BalanceZone_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveActorEndOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_BP_BalanceZone(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BalanceZone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BalanceZone_C")
	}
	static class ABP_BalanceZone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BalanceZone_C>();
	}
};
DUMPER7_ASSERTS_ABP_BalanceZone_C;

SDK_NAMESPACE_END
