#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BalanceHintTrigger

#include "Basic.hpp"

#include "BP_BalanceHintTrigger_classes.hpp"
#include "BP_BalanceHintTrigger_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BalanceHintTrigger.BP_BalanceHintTrigger_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BalanceHintTrigger_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BalanceHintTrigger_C", "ReceiveActorBeginOverlap");

	Params::BP_BalanceHintTrigger_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BalanceHintTrigger.BP_BalanceHintTrigger_C.ExecuteUbergraph_BP_BalanceHintTrigger
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BalanceHintTrigger_C::ExecuteUbergraph_BP_BalanceHintTrigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BalanceHintTrigger_C", "ExecuteUbergraph_BP_BalanceHintTrigger");

	Params::BP_BalanceHintTrigger_C_ExecuteUbergraph_BP_BalanceHintTrigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
