#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BalanceHintTrigger

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BalanceHintTrigger.BP_BalanceHintTrigger_C
// 0x0020 (0x0248 - 0x0228)
class ABP_BalanceHintTrigger_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDataTable*                             PlaystationIcons;                                  // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataTable*                             XBoxIcons;                                         // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataTable*                             KeyboardIcons;                                     // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_BP_BalanceHintTrigger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BalanceHintTrigger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BalanceHintTrigger_C")
	}
	static class ABP_BalanceHintTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BalanceHintTrigger_C>();
	}
};
DUMPER7_ASSERTS_ABP_BalanceHintTrigger_C;

SDK_NAMESPACE_END
