#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EventManager

#include "Basic.hpp"

#include "BP_EventManager_classes.hpp"
#include "BP_EventManager_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EventManager.BP_EventManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EventManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EventManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EventManager.BP_EventManager_C.OnEventLoaded
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EEventType                              EventType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EventManager_C::OnEventLoaded(EEventType EventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EventManager_C", "OnEventLoaded");

	Params::BP_EventManager_C_OnEventLoaded Parms{};

	Parms.EventType = EventType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EventManager.BP_EventManager_C.ToggleEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_EventManager_C::ToggleEvent(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EventManager_C", "ToggleEvent");

	Params::BP_EventManager_C_ToggleEvent Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EventManager.BP_EventManager_C.ExecuteUbergraph_BP_EventManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EventManager_C::ExecuteUbergraph_BP_EventManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EventManager_C", "ExecuteUbergraph_BP_EventManager");

	Params::BP_EventManager_C_ExecuteUbergraph_BP_EventManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
