#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EntitySpawn_Zone

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EntitySpawn_Zone.BP_EntitySpawn_Zone_C
// 0x0028 (0x0250 - 0x0228)
class ABP_EntitySpawn_Zone_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          ClimbBox;                                          // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         FallenPlayers;                                     // 0x0238(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ABacteria_BP_C*                         Bacteria;                                          // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_EntitySpawn_Zone_CollisionComponent_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__BP_EntitySpawn_Zone_Box_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void SpawnEntity();
	void ExecuteUbergraph_BP_EntitySpawn_Zone(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EntitySpawn_Zone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EntitySpawn_Zone_C")
	}
	static class ABP_EntitySpawn_Zone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EntitySpawn_Zone_C>();
	}
};
DUMPER7_ASSERTS_ABP_EntitySpawn_Zone_C;

SDK_NAMESPACE_END
