#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EventManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "S_EventActor_structs.hpp"
#include "Backrooms_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EventManager.BP_EventManager_C
// 0x0030 (0x0250 - 0x0220)
class ABP_EventManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FS_EventActor>                  EventActors;                                       // 0x0230(0x0010)(Edit, BlueprintVisible)
	TArray<class AStaticMeshActor*>               SpawnedActors;                                     // 0x0240(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void ReceiveBeginPlay();
	void OnEventLoaded(EEventType EventType);
	void ToggleEvent(bool Enable);
	void ExecuteUbergraph_BP_EventManager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EventManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EventManager_C")
	}
	static class ABP_EventManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EventManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_EventManager_C;

SDK_NAMESPACE_END
