#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderPiece

#include "Basic.hpp"

#include "BP_LadderPiece_classes.hpp"
#include "BP_LadderPiece_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LadderPiece.BP_LadderPiece_C.OnActorUsed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderPiece_C::OnActorUsed(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderPiece_C", "OnActorUsed");

	Params::BP_LadderPiece_C_OnActorUsed Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LadderPiece.BP_LadderPiece_C.OnBeginHighlight
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void ABP_LadderPiece_C::OnBeginHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderPiece_C", "OnBeginHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderPiece.BP_LadderPiece_C.OnEndHighlight
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void ABP_LadderPiece_C::OnEndHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderPiece_C", "OnEndHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderPiece.BP_LadderPiece_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LadderPiece_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderPiece_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderPiece.BP_LadderPiece_C.ExecuteUbergraph_BP_LadderPiece
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderPiece_C::ExecuteUbergraph_BP_LadderPiece(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderPiece_C", "ExecuteUbergraph_BP_LadderPiece");

	Params::BP_LadderPiece_C_ExecuteUbergraph_BP_LadderPiece Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
