#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Level0Exit

#include "Basic.hpp"

#include "BP_ExitZone_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Level0Exit.BP_Level0Exit_C
// 0x0030 (0x0280 - 0x0250)
class ABP_Level0Exit_C final : public ABP_ExitZone_C
{
public:
	class UStaticMeshComponent*                   Cube4;                                             // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube3;                                             // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube2;                                             // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube1;                                             // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube;                                              // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Level0Exit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Level0Exit_C")
	}
	static class ABP_Level0Exit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Level0Exit_C>();
	}
};
DUMPER7_ASSERTS_ABP_Level0Exit_C;

SDK_NAMESPACE_END
