#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderPiece

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LadderPiece.BP_LadderPiece_C
// 0x0010 (0x0258 - 0x0248)
class ABP_LadderPiece_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget;                                            // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnActorUsed(class ACharacter* Character);
	void OnBeginHighlight();
	void OnEndHighlight();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_LadderPiece(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LadderPiece_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LadderPiece_C")
	}
	static class ABP_LadderPiece_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LadderPiece_C>();
	}
};
DUMPER7_ASSERTS_ABP_LadderPiece_C;

SDK_NAMESPACE_END
