#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderDoor

#include "Basic.hpp"

#include "BP_LadderDoor_classes.hpp"
#include "BP_LadderDoor_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LadderDoor.BP_LadderDoor_C.OnRep_Opened
// (BlueprintCallable, BlueprintEvent)

void ABP_LadderDoor_C::OnRep_Opened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "OnRep_Opened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderDoor.BP_LadderDoor_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_LadderDoor_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderDoor.BP_LadderDoor_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_LadderDoor_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderDoor.BP_LadderDoor_C.OnActorUsed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderDoor_C::OnActorUsed(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "OnActorUsed");

	Params::BP_LadderDoor_C_OnActorUsed Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LadderDoor.BP_LadderDoor_C.OpenDoor
// (BlueprintCallable, BlueprintEvent)

void ABP_LadderDoor_C::OpenDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "OpenDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderDoor.BP_LadderDoor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LadderDoor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderDoor.BP_LadderDoor_C.MC_Sound
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderDoor_C::MC_Sound(class USoundBase* Sound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "MC_Sound");

	Params::BP_LadderDoor_C_MC_Sound Parms{};

	Parms.Sound = Sound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LadderDoor.BP_LadderDoor_C.ExecuteUbergraph_BP_LadderDoor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderDoor_C::ExecuteUbergraph_BP_LadderDoor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderDoor_C", "ExecuteUbergraph_BP_LadderDoor");

	Params::BP_LadderDoor_C_ExecuteUbergraph_BP_LadderDoor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
