#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderManager

#include "Basic.hpp"

#include "BP_LadderManager_classes.hpp"
#include "BP_LadderManager_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LadderManager.BP_LadderManager_C.FoundLadder
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_LadderManager_C::FoundLadder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderManager_C", "FoundLadder");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderManager.BP_LadderManager_C.SetLadders
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderManager_C::SetLadders(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderManager_C", "SetLadders");

	Params::BP_LadderManager_C_SetLadders Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LadderManager.BP_LadderManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LadderManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LadderManager.BP_LadderManager_C.ExecuteUbergraph_BP_LadderManager
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LadderManager_C::ExecuteUbergraph_BP_LadderManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LadderManager_C", "ExecuteUbergraph_BP_LadderManager");

	Params::BP_LadderManager_C_ExecuteUbergraph_BP_LadderManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
