#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ladder

#include "Basic.hpp"

#include "BP_Ladder_classes.hpp"
#include "BP_Ladder_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Ladder.BP_Ladder_C.OnRep_UpdateCount
// (BlueprintCallable, BlueprintEvent)

void ABP_Ladder_C::OnRep_UpdateCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "OnRep_UpdateCount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ladder.BP_Ladder_C.RefreshLadders
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ladder_C::RefreshLadders(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "RefreshLadders");

	Params::BP_Ladder_C_RefreshLadders Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ladder.BP_Ladder_C.ResetControlRotation__FinishedFunc
// (BlueprintEvent)

void ABP_Ladder_C::ResetControlRotation__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "ResetControlRotation__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ladder.BP_Ladder_C.ResetControlRotation__UpdateFunc
// (BlueprintEvent)

void ABP_Ladder_C::ResetControlRotation__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "ResetControlRotation__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ladder.BP_Ladder_C.OnActorUsed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ladder_C::OnActorUsed(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "OnActorUsed");

	Params::BP_Ladder_C_OnActorUsed Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ladder.BP_Ladder_C.MC_Sound
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Ladder_C::MC_Sound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "MC_Sound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ladder.BP_Ladder_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Ladder_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ladder.BP_Ladder_C.ExecuteUbergraph_BP_Ladder
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ladder_C::ExecuteUbergraph_BP_Ladder(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ladder_C", "ExecuteUbergraph_BP_Ladder");

	Params::BP_Ladder_C_ExecuteUbergraph_BP_Ladder Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
