#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LadderDoor.BP_LadderDoor_C
// 0x0028 (0x0270 - 0x0248)
class ABP_LadderDoor_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Open_C18602FD496D06C0331F5A926BAF0D59;  // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_C18602FD496D06C0331F5A926BAF0D59; // 0x025C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25D[0x3];                                      // 0x025D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Opened;                                            // 0x0268(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void OnRep_Opened();
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void OnActorUsed(class ACharacter* Character);
	void OpenDoor();
	void ReceiveBeginPlay();
	void MC_Sound(class USoundBase* Sound);
	void ExecuteUbergraph_BP_LadderDoor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LadderDoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LadderDoor_C")
	}
	static class ABP_LadderDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LadderDoor_C>();
	}
};
DUMPER7_ASSERTS_ABP_LadderDoor_C;

SDK_NAMESPACE_END
