#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Note

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Note.BP_Note_C
// 0x0018 (0x0260 - 0x0248)
class ABP_Note_C final : public AClientInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTexture*                               NoteTexture;                                       // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   NoteRow;                                           // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void OnActorUsed(class ACharacter* Character);
	void ExecuteUbergraph_BP_Note(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Note_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Note_C")
	}
	static class ABP_Note_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Note_C>();
	}
};
DUMPER7_ASSERTS_ABP_Note_C;

SDK_NAMESPACE_END
