#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PitfallsHint_Trigger

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PitfallsHint_Trigger.BP_PitfallsHint_Trigger_C
// 0x0008 (0x0230 - 0x0228)
class ABP_PitfallsHint_Trigger_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BndEvt__BP_PitfallsHint_Trigger_CollisionComponent_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_BP_PitfallsHint_Trigger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PitfallsHint_Trigger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PitfallsHint_Trigger_C")
	}
	static class ABP_PitfallsHint_Trigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PitfallsHint_Trigger_C>();
	}
};
DUMPER7_ASSERTS_ABP_PitfallsHint_Trigger_C;

SDK_NAMESPACE_END
