#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rope_Zone

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Rope_Zone.BP_Rope_Zone_C
// 0x0008 (0x0230 - 0x0228)
class ABP_Rope_Zone_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveActorEndOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_BP_Rope_Zone(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Rope_Zone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Rope_Zone_C")
	}
	static class ABP_Rope_Zone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Rope_Zone_C>();
	}
};
DUMPER7_ASSERTS_ABP_Rope_Zone_C;

SDK_NAMESPACE_END
