#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Side_table_D

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Side_table_D.BP_Side_table_D_C
// 0x0020 (0x0240 - 0x0220)
class ABP_Side_table_D_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Side_table_D_Door_L;                               // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Side_table_D_Door_R;                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Side_table_D;                                      // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Side_table_D_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Side_table_D_C")
	}
	static class ABP_Side_table_D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Side_table_D_C>();
	}
};
DUMPER7_ASSERTS_ABP_Side_table_D_C;

SDK_NAMESPACE_END
