#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Stairs_Module

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Stairs_Module.BP_Stairs_Module_C
// 0x0008 (0x0228 - 0x0220)
class ABP_Stairs_Module_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StairsModule;                                      // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Stairs_Module_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Stairs_Module_C")
	}
	static class ABP_Stairs_Module_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Stairs_Module_C>();
	}
};
DUMPER7_ASSERTS_ABP_Stairs_Module_C;

SDK_NAMESPACE_END
