#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TimeStampCapture

#include "Basic.hpp"

#include "BP_TimeStampCapture_classes.hpp"
#include "BP_TimeStampCapture_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TimeStampCapture.BP_TimeStampCapture_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TimeStampCapture_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TimeStampCapture_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TimeStampCapture.BP_TimeStampCapture_C.Test
// (BlueprintCallable, BlueprintEvent)

void ABP_TimeStampCapture_C::Test()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TimeStampCapture_C", "Test");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TimeStampCapture.BP_TimeStampCapture_C.ExecuteUbergraph_BP_TimeStampCapture
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TimeStampCapture_C::ExecuteUbergraph_BP_TimeStampCapture(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TimeStampCapture_C", "ExecuteUbergraph_BP_TimeStampCapture");

	Params::BP_TimeStampCapture_C_ExecuteUbergraph_BP_TimeStampCapture Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
