#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vent

#include "Basic.hpp"

#include "BP_Vent_classes.hpp"
#include "BP_Vent_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Vent.BP_Vent_C.OnRep_WasBroken
// (BlueprintCallable, BlueprintEvent)

void ABP_Vent_C::OnRep_WasBroken()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "OnRep_WasBroken");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vent.BP_Vent_C.Damage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Vent_C::Damage(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "Damage");

	Params::BP_Vent_C_Damage Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vent.BP_Vent_C.OnUsed
// (BlueprintCallable, BlueprintEvent)

void ABP_Vent_C::OnUsed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "OnUsed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vent.BP_Vent_C.MC_Break
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Vent_C::MC_Break()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "MC_Break");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vent.BP_Vent_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Vent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vent.BP_Vent_C.ExecuteUbergraph_BP_Vent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Vent_C::ExecuteUbergraph_BP_Vent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vent_C", "ExecuteUbergraph_BP_Vent");

	Params::BP_Vent_C_ExecuteUbergraph_BP_Vent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
