#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wall_4m

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Wall_4m.BP_Wall_4m_C
// 0x0018 (0x0238 - 0x0220)
class ABP_Wall_4m_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wall_4m_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wall_4m_C")
	}
	static class ABP_Wall_4m_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Wall_4m_C>();
	}
};
DUMPER7_ASSERTS_ABP_Wall_4m_C;

SDK_NAMESPACE_END
