#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wall_Rectangle_2m_level0

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Wall_Rectangle_2m_level0.BP_Wall_Rectangle_2m_level0_C
// 0x0018 (0x0238 - 0x0220)
class ABP_Wall_Rectangle_2m_level0_C final : public AActor
{
public:
	class UNavModifierComponent*                  NavModifier;                                       // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wall_Rectangle_2m_level0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wall_Rectangle_2m_level0_C")
	}
	static class ABP_Wall_Rectangle_2m_level0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Wall_Rectangle_2m_level0_C>();
	}
};
DUMPER7_ASSERTS_ABP_Wall_Rectangle_2m_level0_C;

SDK_NAMESPACE_END
