#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_HISM

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPP_HISM.BPP_HISM_C.TODO_SetBBOxOfActor
// 0x002C (0x002C - 0x0000)
struct BPP_HISM_C_TODO_SetBBOxOfActor final
{
public:
	struct FVector                                MinLocation;                                       // 0x0000(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MaxLocation;                                       // 0x000C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPP_HISM_C_TODO_SetBBOxOfActor;

// Function BPP_HISM.BPP_HISM_C.SetMaxDrawDistance
// 0x0010 (0x0010 - 0x0000)
struct BPP_HISM_C_SetMaxDrawDistance final
{
public:
	TArray<class UStaticMeshComponent*>           K2Node_MakeArray_Array;                            // 0x0000(0x0010)(ReferenceParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BPP_HISM_C_SetMaxDrawDistance;

// Function BPP_HISM.BPP_HISM_C.UserConstructionScript
// 0x0018 (0x0018 - 0x0000)
struct BPP_HISM_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 CallFunc_AddInstances_ReturnValue;                 // 0x0008(0x0010)(ReferenceParm)
};
DUMPER7_ASSERTS_BPP_HISM_C_UserConstructionScript;

// Function BPP_HISM.BPP_HISM_C.ExecuteUbergraph_BPP_HISM
// 0x0004 (0x0004 - 0x0000)
struct BPP_HISM_C_ExecuteUbergraph_BPP_HISM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPP_HISM_C_ExecuteUbergraph_BPP_HISM;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
