#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_HISM

#include "Basic.hpp"

#include "BPP_HISM_classes.hpp"
#include "BPP_HISM_parameters.hpp"


SDK_NAMESPACE_START

// Function BPP_HISM.BPP_HISM_C.TODO_SetBBOxOfActor
// (Public, BlueprintCallable, BlueprintEvent)

void ABPP_HISM_C::TODO_SetBBOxOfActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_HISM_C", "TODO_SetBBOxOfActor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_HISM.BPP_HISM_C.SetMaxDrawDistance
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABPP_HISM_C::SetMaxDrawDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_HISM_C", "SetMaxDrawDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_HISM.BPP_HISM_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABPP_HISM_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_HISM_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_HISM.BPP_HISM_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPP_HISM_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_HISM_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_HISM.BPP_HISM_C.ExecuteUbergraph_BPP_HISM
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPP_HISM_C::ExecuteUbergraph_BPP_HISM(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_HISM_C", "ExecuteUbergraph_BPP_HISM");

	Params::BPP_HISM_C_ExecuteUbergraph_BPP_HISM Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
