#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_ISM

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPP_ISM.BPP_ISM_C
// 0x0050 (0x0270 - 0x0220)
class ABPP_ISM_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UInstancedStaticMeshComponent*          InstancedStaticMesh;                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FTransform>                     Instance_Transforms;                               // 0x0230(0x0010)(Edit, BlueprintVisible)
	class UStaticMesh*                            Static_Mesh;                                       // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Cull_Distance_Enable;                              // 0x0248(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Cull_Distance_Falloff_Percentage;                  // 0x024C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCullDistanceSizePair>          Cull_Distances;                                    // 0x0250(0x0010)(Edit, BlueprintVisible)
	class FName                                   Collision_Profile_Name;                            // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             Collision_Enabled_Enum;                            // 0x0268(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetMaxDrawDistance();
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BPP_ISM(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPP_ISM_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPP_ISM_C")
	}
	static class ABPP_ISM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPP_ISM_C>();
	}
};
DUMPER7_ASSERTS_ABPP_ISM_C;

SDK_NAMESPACE_END
