#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_ISM

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPP_ISM.BPP_ISM_C.SetMaxDrawDistance
// 0x0010 (0x0010 - 0x0000)
struct BPP_ISM_C_SetMaxDrawDistance final
{
public:
	TArray<class UStaticMeshComponent*>           K2Node_MakeArray_Array;                            // 0x0000(0x0010)(ReferenceParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BPP_ISM_C_SetMaxDrawDistance;

// Function BPP_ISM.BPP_ISM_C.UserConstructionScript
// 0x0018 (0x0018 - 0x0000)
struct BPP_ISM_C_UserConstructionScript final
{
public:
	TArray<int32>                                 CallFunc_AddInstances_ReturnValue;                 // 0x0000(0x0010)(ReferenceParm)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPP_ISM_C_UserConstructionScript;

// Function BPP_ISM.BPP_ISM_C.ExecuteUbergraph_BPP_ISM
// 0x0004 (0x0004 - 0x0000)
struct BPP_ISM_C_ExecuteUbergraph_BPP_ISM final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPP_ISM_C_ExecuteUbergraph_BPP_ISM;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
