#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_ISM

#include "Basic.hpp"

#include "BPP_ISM_classes.hpp"
#include "BPP_ISM_parameters.hpp"


SDK_NAMESPACE_START

// Function BPP_ISM.BPP_ISM_C.SetMaxDrawDistance
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABPP_ISM_C::SetMaxDrawDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_ISM_C", "SetMaxDrawDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_ISM.BPP_ISM_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABPP_ISM_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_ISM_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_ISM.BPP_ISM_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPP_ISM_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_ISM_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPP_ISM.BPP_ISM_C.ExecuteUbergraph_BPP_ISM
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPP_ISM_C::ExecuteUbergraph_BPP_ISM(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPP_ISM_C", "ExecuteUbergraph_BPP_ISM");

	Params::BPP_ISM_C_ExecuteUbergraph_BPP_ISM Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
