#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Level0

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Level0.Level0_C
// 0x0000 (0x0228 - 0x0228)
class ALevel0_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Level0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Level0_C")
	}
	static class ALevel0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALevel0_C>();
	}
};
DUMPER7_ASSERTS_ALevel0_C;

SDK_NAMESPACE_END
