#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Level0

#include "Basic.hpp"

#include "MP_Level0_classes.hpp"
#include "MP_Level0_parameters.hpp"


SDK_NAMESPACE_START

// Function MP_Level0.MP_Level0_C.LoadCheckpoints
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AMP_Level0_C::LoadCheckpoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "LoadCheckpoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Level0.MP_Level0_C.ChoosePlayerStart
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class AActor* AMP_Level0_C::ChoosePlayerStart(class AController* Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "ChoosePlayerStart");

	Params::MP_Level0_C_ChoosePlayerStart Parms{};

	Parms.Player_0 = Player_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MP_Level0.MP_Level0_C.SetExit
// (Public, BlueprintCallable, BlueprintEvent)

void AMP_Level0_C::SetExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "SetExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Level0.MP_Level0_C.ShouldRetrySpawn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Retry                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMP_Level0_C::ShouldRetrySpawn(bool* Retry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "ShouldRetrySpawn");

	Params::MP_Level0_C_ShouldRetrySpawn Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Retry != nullptr)
		*Retry = Parms.Retry;
}


// Function MP_Level0.MP_Level0_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AMP_Level0_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Level0.MP_Level0_C.HandleStartingNewPlayer
// (Event, Public, BlueprintEvent)
// Parameters:
// class APlayerController*                NewPlayer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMP_Level0_C::HandleStartingNewPlayer(class APlayerController* NewPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "HandleStartingNewPlayer");

	Params::MP_Level0_C_HandleStartingNewPlayer Parms{};

	Parms.NewPlayer = NewPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MP_Level0.MP_Level0_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMP_Level0_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Level0.MP_Level0_C.OnPlayerSpawn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABPCharacter_Demo_C*              Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMP_Level0_C::OnPlayerSpawn(class ABPCharacter_Demo_C* Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "OnPlayerSpawn");

	Params::MP_Level0_C_OnPlayerSpawn Parms{};

	Parms.Player_0 = Player_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MP_Level0.MP_Level0_C.UnlockSurvivalistAfter15min
// (BlueprintCallable, BlueprintEvent)

void AMP_Level0_C::UnlockSurvivalistAfter15min()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "UnlockSurvivalistAfter15min");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Level0.MP_Level0_C.ExecuteUbergraph_MP_Level0
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMP_Level0_C::ExecuteUbergraph_MP_Level0(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Level0_C", "ExecuteUbergraph_MP_Level0");

	Params::MP_Level0_C_ExecuteUbergraph_MP_Level0 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
