#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Level0

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MP_GameMode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MP_Level0.MP_Level0_C
// 0x0018 (0x03A8 - 0x0390)
class AMP_Level0_C final : public AMP_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MP_Level0_C;                        // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABPCharacter_Demo_C*                    Player;                                            // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasFoundFirstKey;                                  // 0x03A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ManillaUnlocked;                                   // 0x03A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void LoadCheckpoints();
	class AActor* ChoosePlayerStart(class AController* Player_0);
	void SetExit();
	void ShouldRetrySpawn(bool* Retry);
	void UserConstructionScript();
	void HandleStartingNewPlayer(class APlayerController* NewPlayer);
	void ReceiveBeginPlay();
	void OnPlayerSpawn(class ABPCharacter_Demo_C* Player_0);
	void UnlockSurvivalistAfter15min();
	void ExecuteUbergraph_MP_Level0(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MP_Level0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MP_Level0_C")
	}
	static class AMP_Level0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMP_Level0_C>();
	}
};
DUMPER7_ASSERTS_AMP_Level0_C;

SDK_NAMESPACE_END
