#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pitfalls

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Pitfalls.Pitfalls_C
// 0x0000 (0x0228 - 0x0228)
class APitfalls_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Pitfalls_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Pitfalls_C")
	}
	static class APitfalls_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APitfalls_C>();
	}
};
DUMPER7_ASSERTS_APitfalls_C;

SDK_NAMESPACE_END
