#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_EventActor

#include "Basic.hpp"

#include "Backrooms_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_EventActor.S_EventActor
// 0x0050 (0x0050 - 0x0000)
struct FS_EventActor final
{
public:
	class UStaticMesh*                            Mesh_11_E4689B1E498629694EECF9AB83AEE368;          // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Material_14_277B844C41CAFA57E4C53993B1EAED9E;      // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             Transform_5_E53FE1ED4A2A473FB85125852338367C;      // 0x0010(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
	EEventType                                    Event_8_80E2A2D64571D48E0FCD46A9B904127F;          // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FS_EventActor;

SDK_NAMESPACE_END
