#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_Note

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_Note.S_Note
// 0x0018 (0x0018 - 0x0000)
struct FS_Note final
{
public:
	class FText                                   Subtitle_20_A273180646B0B51FD37B16BB0CBE6C3E;      // 0x0000(0x0018)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FS_Note;

SDK_NAMESPACE_END
