#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: T_Wall_BP_level0

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass T_Wall_BP_level0.T_Wall_BP_level0_C
// 0x0008 (0x0228 - 0x0220)
class AT_Wall_BP_level0_C final : public AActor
{
public:
	class USceneComponent*                        SharedRoot;                                        // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("T_Wall_BP_level0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"T_Wall_BP_level0_C")
	}
	static class AT_Wall_BP_level0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AT_Wall_BP_level0_C>();
	}
};
DUMPER7_ASSERTS_AT_Wall_BP_level0_C;

SDK_NAMESPACE_END
