#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wall_BP_3_level0

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Wall_BP_3_level0.Wall_BP_3_level0_C
// 0x0008 (0x0228 - 0x0220)
class AWall_BP_3_level0_C final : public AActor
{
public:
	class USceneComponent*                        SharedRoot;                                        // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Wall_BP_3_level0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Wall_BP_3_level0_C")
	}
	static class AWall_BP_3_level0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWall_BP_3_level0_C>();
	}
};
DUMPER7_ASSERTS_AWall_BP_3_level0_C;

SDK_NAMESPACE_END
